server:
  port: 8080

spring:
  application:
    name: patient
  datasource:
    url: jdbc:mysql://localhost:3306/patientdb
    username: root # Database username
    password: test # Database password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka